### ISSUE TITLE
StrictPasswordChangeForm should treat old_password as auth attempt

### ISSUE THREAD

**Issue by neonbunny** [dreamsolution/django-auth-policy#8]
It's possible to brute-force a user's password (if they've left their session logged in) by trying various passwords as their "old password" in the StrictPasswordChangeForm. This form should pass the old_password value through the AUTHENTICATION_POLICIES to prevent this.

**Comment by rudolphfroger** [comment]
Thanks, that's a nice issue to think about.

Currently the authentication lock-out is determined from the number of recent LoginAttempt records that match the right criteria. However storing invalid 'old password attempts' in the LoginAttempt table doesn't seem the right place to store this information because that table is meant to log real login attempts. We could split off the lock-out information into a separate table.

**Comment by rudolphfroger** [comment]
On second thoughts, we could store failed 'old_password' validations in the 'PasswordChange' model.

**Comment by rudolphfroger** [comment]
Rate limiting should be done on user login, password changes and password resets. My current opinion is that this rate limiting is probably better implemented in a different python package or may be a simple Gist to be used as inspiration for project specific implementations.
